"""Command line: run an agent on a task, review its diff, then (optionally) open a PR.

    python -m agent_team dev "Add a /health endpoint to web/ with a test"

Flow:
  1. Fresh clone of the repo inside the agent's sandbox.
  2. The agent works there (it never touches your files or holds a GitHub token).
  3. You see the diff. Only if you approve, it's applied to a new branch on your
     machine, pushed with your `gh` login, and a pull request is opened, where the
     DevSecOps pipeline checks it before anything reaches main.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import time
from pathlib import Path

from openai import OpenAI

from agent_team.agent import SYSTEM_PROMPTS, Agent, RunResult
from agent_team.config import REPO_ROOT, settings_for
from agent_team.sandbox import WORKDIR, Sandbox
from agent_team.tools import Toolbox

# Agents may not change their own guardrails or the pipeline that checks them.
PROTECTED_PREFIXES = (".github/", "infra/", "agents/")
RUNS_DIR = REPO_ROOT / "runs"


def protected_changes(paths: list[str]) -> list[str]:
    return [p for p in paths if p.startswith(PROTECTED_PREFIXES)]


def prepare_workspace(sandbox: Sandbox, repo_url: str) -> None:
    res = sandbox.sh(
        f"rm -rf {WORKDIR} && git clone --quiet --depth 1 {repo_url} {WORKDIR}",
        workdir="/workspace",
        timeout=180,
    )
    if not res.ok:
        raise RuntimeError(f"could not clone {repo_url} in the sandbox:\n{res.output}")


def collect_diff(sandbox: Sandbox) -> tuple[list[str], str, str]:
    """Stage everything in the sandbox and return (changed paths, stat, full patch)."""
    sandbox.exec(["git", "add", "-A"])
    names = sandbox.exec(["git", "diff", "--cached", "--name-only"]).output.split()
    stat = sandbox.exec(["git", "diff", "--cached", "--stat"]).output
    patch = sandbox.exec(["git", "diff", "--cached", "--binary"]).output
    return names, stat, patch


def _git(*args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(REPO_ROOT), *args], check=True, capture_output=True, text=True
    ).stdout.strip()


def open_pull_request(role: str, task: str, result: RunResult, patch_file: Path) -> str:
    if _git("status", "--porcelain", "--untracked-files=no"):
        raise RuntimeError("your repo has uncommitted changes; commit or stash them first")
    branch = f"agent/{role}-{time.strftime('%Y%m%d-%H%M%S')}"
    start = _git("rev-parse", "--abbrev-ref", "HEAD")
    _git("fetch", "--quiet", "origin", "main")
    _git("switch", "--quiet", "-c", branch, "origin/main")
    try:
        _git("apply", "--index", str(patch_file))
        title = f"agent({role}): {task.strip().splitlines()[0][:60]}"
        _git("commit", "--quiet", "-m", title, "-m", result.summary)
        _git("push", "--quiet", "-u", "origin", branch)
        body = (
            f"**Task:** {task}\n\n**Agent summary:**\n{result.summary}\n\n"
            f"Steps: {result.steps} · tokens in/out: "
            f"{result.prompt_tokens}/{result.completion_tokens}\n\n"
            f"_Generated by the {role} agent. Review the diff before merging._"
        )
        url = subprocess.run(
            [
                "gh",
                "pr",
                "create",
                "--base",
                "main",
                "--head",
                branch,
                "--title",
                title,
                "--body",
                body,
            ],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    finally:
        _git("switch", "--quiet", start)
    return url


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="agent-team", description=__doc__.split("\n")[0])
    parser.add_argument("role", choices=sorted(SYSTEM_PROMPTS))
    parser.add_argument("task", help="what the agent should do, in plain language")
    parser.add_argument("--max-steps", type=int, help="override AGENT_MAX_STEPS")
    parser.add_argument(
        "--allow-protected",
        action="store_true",
        help=f"allow changes under {', '.join(PROTECTED_PREFIXES)} (you'll still review)",
    )
    args = parser.parse_args(argv)

    settings = settings_for(args.role)
    sandbox = Sandbox(settings.sandbox)
    if not sandbox.is_running():
        print(
            f"Sandbox {settings.sandbox} isn't running. Start it with:\n"
            "  cd infra && docker compose --profile sandbox up -d --build",
            file=sys.stderr,
        )
        return 2

    print(f"▶ Preparing a fresh clone in {settings.sandbox} ...")
    prepare_workspace(sandbox, settings.repo_url)

    client = OpenAI(base_url=settings.base_url, api_key=settings.api_key, max_retries=2)
    agent = Agent(
        client,
        settings.model,
        Toolbox(sandbox),
        SYSTEM_PROMPTS[args.role],
        max_steps=args.max_steps or settings.max_steps,
    )
    print(f"▶ {args.role} agent working (model alias: {settings.model}) ...\n")
    result = agent.run(args.task)

    print("\n" + "=" * 60)
    print(
        f"Finished: {result.finished} · steps: {result.steps} · tokens in/out: "
        f"{result.prompt_tokens}/{result.completion_tokens}"
    )
    print(f"Summary:\n{result.summary}\n")

    names, stat, patch = collect_diff(sandbox)
    if not names:
        print("No file changes.")
        return 0 if result.finished else 1

    RUNS_DIR.mkdir(exist_ok=True)
    patch_file = RUNS_DIR / f"{time.strftime('%Y%m%d-%H%M%S')}-{args.role}.patch"
    patch_file.write_text(patch if patch.endswith("\n") else patch + "\n", encoding="utf-8")
    print(f"Changes:\n{stat}\nFull diff saved to {patch_file.relative_to(REPO_ROOT)}")

    blocked = protected_changes(names)
    if blocked and not args.allow_protected:
        print("\n⛔ The agent changed protected paths, so no PR will be opened:")
        print("\n".join(f"   {p}" for p in blocked))
        print("Review the patch; rerun with --allow-protected only if you intend this.")
        return 1

    answer = input("\nOpen a pull request with these changes? Review the diff first. [y/N] ")
    if answer.strip().lower() != "y":
        print("Not opening a PR. The patch file is kept for reference.")
        return 0

    url = open_pull_request(args.role, args.task, result, patch_file)
    print(f"✅ Pull request opened: {url}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
