"""Command line: run an agent, review its changes, then (optionally) open a PR.

    python -m agent_team dev "Add a /health endpoint to web/ with a test"
    python -m agent_team qa --pr 3
    python -m agent_team qa --pr 3 "Focus on input validation"

Flow:
  1. A fresh clone of the repo (and, for QA, the pull request) inside the agent's sandbox.
  2. The agent works there; it never touches your files or holds a GitHub token.
  3. You see the diff (and, for QA, a bug report). Only if you approve, changes go to
     a new branch pushed with your `gh` login and a PR is opened, where the DevSecOps
     pipeline checks them before anything is merged.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import time
from pathlib import Path

from openai import OpenAI

from agent_team import github, qa
from agent_team.agent import SYSTEM_PROMPTS, Agent, RunResult
from agent_team.config import REPO_ROOT, settings_for
from agent_team.sandbox import WORKDIR, Sandbox
from agent_team.tools import Toolbox, is_test_path

# Agents may not change their own guardrails or the pipeline that checks them.
PROTECTED_PREFIXES = (".github/", "infra/", "agents/")
RUNS_DIR = REPO_ROOT / "runs"


def protected_changes(paths: list[str]) -> list[str]:
    return [p for p in paths if p.startswith(PROTECTED_PREFIXES)]


def disallowed_changes(role: str, paths: list[str], allow_protected: bool) -> list[str]:
    """Paths this role must not change. QA's test-only rule can't be overridden."""
    blocked = [] if allow_protected else protected_changes(paths)
    if role == "qa":
        blocked += [p for p in paths if not is_test_path(p) and p not in blocked]
    return blocked


def prepare_workspace(sandbox: Sandbox, repo_url: str) -> None:
    res = sandbox.exec(["rm", "-rf", WORKDIR], workdir="/workspace")
    if res.ok:
        res = sandbox.exec(
            ["git", "clone", "--quiet", "--depth", "1", repo_url, WORKDIR],
            workdir="/workspace",
            timeout=180,
        )
    if not res.ok:
        raise RuntimeError(f"could not clone {repo_url} in the sandbox:\n{res.output}")


def collect_diff(sandbox: Sandbox) -> tuple[list[str], str, str]:
    """Stage everything in the sandbox and return (changed paths, stat, full patch)."""
    sandbox.exec(["git", "add", "-A"])
    names = sandbox.exec(["git", "diff", "--cached", "--name-only"]).output.split()
    stat = sandbox.exec(["git", "diff", "--cached", "--stat"]).output
    patch = sandbox.exec(["git", "diff", "--cached", "--binary"]).output
    return names, stat, patch


def _git(*args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(REPO_ROOT), *args], check=True, capture_output=True, text=True
    ).stdout.strip()


def open_pull_request(role: str, title: str, body: str, patch_file: Path, base: str) -> str:
    if _git("status", "--porcelain", "--untracked-files=no"):
        raise RuntimeError("your repo has uncommitted changes; commit or stash them first")
    branch = f"agent/{role}-{time.strftime('%Y%m%d-%H%M%S')}"
    start = _git("rev-parse", "--abbrev-ref", "HEAD")
    _git("fetch", "--quiet", "origin", base)
    _git("switch", "--quiet", "-c", branch, f"origin/{base}")
    try:
        _git("apply", "--index", str(patch_file))
        _git("commit", "--quiet", "-m", title)
        _git("push", "--quiet", "-u", "origin", branch)
        return github.create_pr(base, branch, title, body)
    finally:
        _git("switch", "--quiet", start)


def _ask(question: str) -> bool:
    return input(f"\n{question} [y/N] ").strip().lower() == "y"


def _stamp() -> str:
    return time.strftime("%Y%m%d-%H%M%S")


def _footer(result: RunResult, role: str) -> str:
    return (
        f"Steps: {result.steps} · tokens in/out: "
        f"{result.prompt_tokens}/{result.completion_tokens}\n\n"
        f"_Generated by the {role} agent. Review the diff before merging._"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="agent-team", description=__doc__.split("\n")[0])
    parser.add_argument("role", choices=sorted(SYSTEM_PROMPTS))
    parser.add_argument("task", nargs="?", default="", help="what to do (dev), or extra focus (qa)")
    parser.add_argument("--pr", type=int, help="pull request number for the QA agent to test")
    parser.add_argument("--max-steps", type=int, help="override AGENT_MAX_STEPS")
    parser.add_argument(
        "--allow-protected",
        action="store_true",
        help=f"allow changes under {', '.join(PROTECTED_PREFIXES)} (you'll still review)",
    )
    args = parser.parse_args(argv)

    if args.role == "qa" and not args.pr:
        parser.error("the qa agent needs --pr NUMBER")
    if args.role != "qa" and args.pr:
        parser.error("--pr is only used by the qa agent")
    if args.role != "qa" and not args.task.strip():
        parser.error(f"the {args.role} agent needs a task")

    settings = settings_for(args.role)
    sandbox = Sandbox(settings.sandbox)
    if not sandbox.is_running():
        print(
            f"Sandbox {settings.sandbox} isn't running. Start it with:\n"
            "  cd infra && docker compose --profile sandbox up -d",
            file=sys.stderr,
        )
        return 2

    pr = None
    if args.role == "qa":
        pr = github.get_pr(args.pr)
        if pr.state == "CLOSED":
            print(f"PR #{pr.number} was closed without merging; nothing to test.")
            return 1
        print(f"▶ Checking out PR #{pr.number} ({pr.state.lower()}) in {settings.sandbox} ...")
        pr_stat, pr_diff = qa.prepare_pr_workspace(sandbox, settings.repo_url, pr)
        task = qa.build_qa_task(pr, pr_stat, pr_diff, args.task)
        toolbox = Toolbox(
            sandbox, can_write=is_test_path, write_rule=qa.WRITE_RULE, bug_reports=True
        )
    else:
        print(f"▶ Preparing a fresh clone in {settings.sandbox} ...")
        prepare_workspace(sandbox, settings.repo_url)
        task = args.task
        toolbox = Toolbox(sandbox)

    client = OpenAI(base_url=settings.base_url, api_key=settings.api_key, max_retries=2)
    agent = Agent(
        client,
        settings.model,
        toolbox,
        SYSTEM_PROMPTS[args.role],
        max_steps=args.max_steps or settings.max_steps,
    )
    print(f"▶ {args.role} agent working (model alias: {settings.model}) ...\n")
    result = agent.run(task)

    print("\n" + "=" * 60)
    print(
        f"Finished: {result.finished} · steps: {result.steps} · tokens in/out: "
        f"{result.prompt_tokens}/{result.completion_tokens}"
    )

    names, stat, patch = collect_diff(sandbox)
    RUNS_DIR.mkdir(exist_ok=True)
    stamp = _stamp()

    report_file = None
    if pr is not None:
        report = qa.build_report(pr, result, toolbox.bugs, stat)
        report_file = RUNS_DIR / f"{stamp}-qa-pr{pr.number}.md"
        report_file.write_text(report, encoding="utf-8")
        print(f"\n{report}\nReport saved to {report_file.relative_to(REPO_ROOT)}")
    else:
        print(f"Summary:\n{result.summary}\n")

    pr_url = None
    if names:
        patch_file = RUNS_DIR / f"{stamp}-{args.role}.patch"
        patch_file.write_text(patch if patch.endswith("\n") else patch + "\n", encoding="utf-8")
        print(f"Changes:\n{stat}\nFull diff saved to {patch_file.relative_to(REPO_ROOT)}")

        blocked = disallowed_changes(args.role, names, args.allow_protected)
        base = pr.test_branch_target() if pr is not None else "main"
        if blocked:
            print(f"\n⛔ The {args.role} agent changed files it isn't allowed to; no PR:")
            print("\n".join(f"   {p}" for p in blocked))
        elif base is None:
            print("\nℹ️  Can't open a follow-up PR for this PR (fork or closed); patch kept.")
        elif _ask(f"Open a pull request into '{base}' with these changes? Review the diff first."):
            if pr is not None:
                title = f"agent(qa): tests for #{pr.number} {pr.title}"[:72]
                body = f"Adds QA tests for #{pr.number}.\n\n{report}\n{_footer(result, 'qa')}"
            else:
                title = f"agent({args.role}): {args.task.strip().splitlines()[0][:60]}"
                body = (
                    f"**Task:** {args.task}\n\n**Agent summary:**\n{result.summary}\n\n"
                    f"{_footer(result, args.role)}"
                )
            pr_url = open_pull_request(args.role, title, body, patch_file, base)
            print(f"✅ Pull request opened: {pr_url}")
        else:
            print("Not opening a PR. The patch file is kept for reference.")
    else:
        print("No file changes.")

    if pr is not None and report_file is not None:
        if _ask(f"Post the QA report as a comment on PR #{pr.number}?"):
            if pr_url:
                with report_file.open("a", encoding="utf-8") as fh:
                    fh.write(f"\nNew tests: {pr_url}\n")
            github.comment_on_pr(pr.number, report_file)
            print(f"✅ Comment posted on {pr.url}")

    return 0 if result.finished else 1


if __name__ == "__main__":
    raise SystemExit(main())
